In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.naive_bayes import *

In [2]:
train = pd.read_csv('train.csv',index_col='PassengerId')
train.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S

In [3]:
l = preprocessing.LabelEncoder()
for i in ['Sex','Embarked']:
    train[i] = l.fit_transform(train[i])

In [4]:
train.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name  Sex   Age  \
PassengerId                                                                 
1                                      Braund, Mr. Owen Harris    1  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0   
3                                       Heikkinen, Miss. Laina    0  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0   
5                                     Allen, Mr. William Henry    1  35.0   

             SibSp  Parch            Ticket     Fare Cabin  Embarked  
PassengerId                                                           
1                1      0         A/5 21171   7.2500   NaN         2  
2                1      0          PC 17599  71.2833   C85         0  
3                0      0  STON/O2. 3101282   7.9250   NaN         2  
4                1      0            113803  53.1000  C123         2  
5                0      0            373450   8.0500   NaN         2

In [5]:
train.isna().sum()

Survived      0
Pclass        0
Name          0
Sex           0
Age           0
SibSp         0
Parch         0
Ticket        0
Fare          0
Cabin       687
Embarked      0
dtype: int64

In [6]:
train['Cabin'].value_counts()

G6             4
C23 C25 C27    4
B96 B98        4
F2             3
C22 C26        3
              ..
B4             1
E31            1
E38            1
B86            1
E77            1
Name: Cabin, Length: 146, dtype: int64

In [7]:
# train['Cabin'] = train.fillna(train['Cabin'].mode(),inplace=True)

In [8]:
train.columns

Index(['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket',
       'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [9]:
train.drop(['Name','Ticket','Cabin'], axis= 1,inplace= True)

In [10]:
train.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
PassengerId                                                              
1                   0       3    1  22.0      1      0   7.2500         2
2                   1       1    0  38.0      1      0  71.2833         0
3                   1       3    0  26.0      0      0   7.9250         2
4                   1       1    0  35.0      1      0  53.1000         2
5                   0       3    1  35.0      0      0   8.0500         2

In [11]:
train['Fare']= np.round(train['Fare'])

In [41]:
arr = train['Age']
arr

PassengerId
1      22.0
2      38.0
3      26.0
4      35.0
5      35.0
       ... 
887    27.0
888    19.0
889    45.0
890    26.0
891    32.0
Name: Age, Length: 889, dtype: float64

In [16]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 1 to 891
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  889 non-null    int64  
 1   Pclass    889 non-null    int64  
 2   Sex       889 non-null    int32  
 3   Age       889 non-null    float64
 4   SibSp     889 non-null    int64  
 5   Parch     889 non-null    int64  
 6   Fare      889 non-null    float64
 7   Embarked  889 non-null    int32  
dtypes: float64(2), int32(2), int64(4)
memory usage: 55.6 KB


In [43]:
train = train.applymap(int)
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 1 to 891
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  889 non-null    int64
 1   Pclass    889 non-null    int64
 2   Sex       889 non-null    int64
 3   Age       889 non-null    int64
 4   SibSp     889 non-null    int64
 5   Parch     889 non-null    int64
 6   Fare      889 non-null    int64
 7   Embarked  889 non-null    int64
dtypes: int64(8)
memory usage: 62.5 KB


In [44]:
features = ['Survived','Fare','Age','Pclass','Sex','SibSp','Parch','Embarked']
score_card = pd.DataFrame(data=[], columns=['features','Accuracy'])

for i in features:
    y = train[i]
    x = train.drop([i], axis = 1)
    x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = .3,random_state = 0)
    clf = BernoulliNB()
    y_predict = clf.fit(x_train,y_train).predict(x_test)
    acc_score = accuracy_score(y_test,y_predict)
    conf_mat = confusion_matrix(y_test,y_predict)
    score_card.loc[len(score_card)] = [i, acc_score]
    print('The confusion matrix for', i ,'is:', conf_mat)

The confusion matrix for Survived is: [[131  26]
 [ 32  78]]
The confusion matrix for Fare is: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 5 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
The confusion matrix for Age is: [[0 2 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
The confusion matrix for Pclass is: [[ 30   9  31]
 [  9  11  29]
 [ 24   6 118]]
The confusion matrix for Sex is: [[ 49  49]
 [ 19 150]]
The confusion matrix for SibSp is: [[162  19   1   0   0   0   0]
 [ 43  20   2   0   0   0   0]
 [  6   2   0   0   0   0   0]
 [  5   2   0   0   0   0   0]
 [  2   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0]
 [  2   0   0   0   0   0   0]]
The confusion matrix for Parch is: [[182  16   0   0   0]
 [ 30  10   0   0   0]
 [ 22   5   0   0   0]
 [  1   0   0   0   0]
 [  1   0   0   0   0]]
The confusion matrix for Embarked is: [[  1   0  48]
 [  0   0  22]
 [  3   0 193]]


In [45]:
score_card.sort_values(['Accuracy'], ascending= False)

features  Accuracy
0  Survived  0.782772
4       Sex  0.745318
7  Embarked  0.726592
6     Parch  0.719101
5     SibSp  0.681648
3    Pclass  0.595506
1      Fare  0.303371
2       Age  0.183521