# 1. Create a 3x3x3 array with random values 

In [3]:
import numpy as np

rand = np.random.random((3,3,3))
rand

array([[[0.95073214, 0.57490884, 0.11540682],
        [0.6070704 , 0.86659658, 0.08240078],
        [0.76005173, 0.90871403, 0.97183158]],

       [[0.65455776, 0.24960645, 0.89743397],
        [0.55251281, 0.98288366, 0.01718117],
        [0.21979484, 0.39579227, 0.64965005]],

       [[0.79741071, 0.03635918, 0.28444765],
        [0.83069431, 0.55442707, 0.80218957],
        [0.62331619, 0.56155197, 0.03503777]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [45]:
print("Checkerboard pattern:")
x = np.zeros((8,8))
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 4. Normalize a 5x5 random matrix

In [14]:
rand = np.random.random((5,5))
print('Original matrix :')
print(rand)
randmax,randmin = rand.max(),rand.min()
rand = (rand-randmin)/(randmax-randmin)
print('After nomalization :')
print(rand)


Original matrix :
[[0.08442785 0.63868527 0.67449384 0.44205017 0.16579163]
 [0.44309128 0.67095973 0.8618699  0.05724028 0.72845902]
 [0.93758931 0.20762157 0.84856096 0.45935555 0.75787423]
 [0.19569533 0.52540134 0.59654301 0.38354502 0.16518804]
 [0.14746799 0.08791321 0.66830748 0.39862013 0.52080508]]
After nomalization :
[[0.03088272 0.66047099 0.70114641 0.43711059 0.1233049 ]
 [0.43829321 0.69713197 0.91398933 0.         0.76244616]
 [1.         0.17082008 0.89887153 0.456768   0.79585929]
 [0.15727291 0.53179029 0.61260104 0.37065383 0.12261928]
 [0.10249084 0.03484179 0.69411924 0.38777785 0.52656934]]


# 5.  How to find common values between two arrays?

In [16]:
arr1 = [4,8,3,9,5]
arr2 = [2,4,6,9,5]
common = np.intersect1d(arr1, arr2)
print(common)

[4 5 9]


# 6.How to get the dates of yesterday, today and tomorrow?

# 7. Consider two random array A and B, check if they are equal

In [17]:
arr1 = np.random.randint(0,20,5)
arr2 = np.random.randint(0,20,5)
arr1 == arr2

array([False, False, False, False, False])

# 8.Create random vector of size 10 and replace the maximum value by 0 

In [23]:
arr = np.random.randint(0, 30, 10)
print('Before:',arr)
arr[arr.argmax()] = 0
print('After max value change by 0:',arr)

Before: [11  9  0  5 14  9 26 11 29  3]
After max value change by 0: [11  9  0  5 14  9 26 11  0  3]


# 9. How to print all the values of an array?

In [18]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(*arr)

1 2 3 4 5 6 7 8 9


# 10.Subtract the mean of each row of a matrix

In [27]:
print("Original matrix:\n")
X = np.random.rand(4, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.85436885 0.54084535 0.11335183 0.30422771 0.97793056 0.28404126
  0.48286864 0.02849563 0.02848603 0.20036308]
 [0.65903193 0.9384489  0.0739217  0.20062755 0.73306297 0.66190495
  0.05879538 0.47163808 0.29123097 0.40266863]
 [0.45518419 0.29331804 0.07208655 0.24804213 0.21714049 0.75209508
  0.58962409 0.14231226 0.61475908 0.67244177]
 [0.08706462 0.12826302 0.58618028 0.70529792 0.80073433 0.65043266
  0.20633335 0.19366041 0.41722124 0.97491148]]

Subtract the mean of each row of the said matrix:

[[ 0.47287095  0.15934746 -0.26814606 -0.07727019  0.59643267 -0.09745664
   0.10137075 -0.35300227 -0.35301187 -0.18113482]
 [ 0.20989883  0.4893158  -0.3752114  -0.24850556  0.28392986  0.21277185
  -0.39033773  0.02250497 -0.15790214 -0.04646448]
 [ 0.04948383 -0.11238233 -0.33361382 -0.15765824 -0.18855988  0.34639471
   0.18392372 -0.26338811  0.20905871  0.2667414 ]
 [-0.38794531 -0.34674691  0.11117035  0.23028799  0.3257244   0.17542273
  -0.26867658 -0.281

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

# 12.How to get the diagonal of a dot product?

In [32]:
a = np.random.randint(0, 10, (2,2))
b = np.random.randint(5, 10, (2,2))
print('vector A:',a)
print('Vector B:',b)
product = np.dot(a,b) 
print(product)
print('The diagonal dot products are :',np.diag(product))

vector A: [[9 3]
 [7 8]]
Vector B: [[8 6]
 [7 8]]
[[ 93  78]
 [112 106]]
The diagonal dot products are : [ 93 106]


# 13.How to find the most frequent value in an array?

In [33]:
x = np.random.randint(5, 50, 20)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[12 12 17 48 17 14  8 22 15 39 16 39 49 35 23 43 24 22 48 47]
Most frequent value in the above array:
12


# 14.How to get the n largest values of an array

In [36]:
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


# 15.How to create a record array from a regular array?